language: node_js
sudo: false
node_js:
- stable
addons:
  firefox: '42.0'
cache:
  directories:
  - node_modules
before_script:
- npm install web-component-tester bower polylint
- bower install
- bower install -s https://${GH_TOKEN}@github.com/Collaborne/collaborne-build-tools.git
- polylint
- export PATH=$PWD/node_modules/.bin:$PATH
script:
- xvfb-run wct
after_success: '[ ${TRAVIS_PULL_REQUEST} = "false" ] && [ ${TRAVIS_BRANCH} = "master" ] && bower_components/collaborne-build-tools/gpages_build.sh Collaborne info@collaborne.com'
env:
  secure: I4xyE9TU1nfz6GgJuoOyxLyoB9MXGSFEung809F+ZgauRkmFpvqvMkbfTTRhaUjrdpjMzcKmWZOCS8oeGg2Azgl+RZ/9qtWchrW1ygHo9BOf4IIW/dSRbRNgfyokamLYCBYoUjob+BN6rLt3jTj+KW86PvceaC/S3h/s3KFohv+Lai+RnJ1ynebJoB37mLctqVBUwDUPo2wWntqugGnnZ6B94doPuSBXay3up6wly5WbpVaVoVM8NdZIww1RVo6cOq/w16+orZhMk0lTmD78qqYbxQyFQb63N4NTQTltyFcV4sOxCpT0TIW7Xr5ArtvEOYsvrG4CYjNcTIR336lN8yIytDm9ryLhuvxOlPnybUUEM4kmeTem5G2jp7umCys+reXpL9W+K8PzgA4tQyWGOCbRvlAS8vZcRhmGWOdBWLEOcCyH/wdg8W0YYx8gS/RKGDEa8IEIXfN0S8htcRGYKcMUxtfd8a9Qp6U9WIN9qOsyo8OFzy7VnWp4aLsfhGKdK1EcdIwh6h/6Dgyi208aYjjdcMrVXFXdad+aPaZ25mQLLMZt+lC5/RFVEj6ZgAZ51GwCet31O/tZqNY+cXoGbyysduZ1Q3vCuONYFkqKv6U0e1SCFMUJD+/ZP83DtlVjoUO9p+YrQarEDmg0/zDuhnqJB27nBFBc6lDlk+lOxUA=
